Modified gitignore to avoid tracking .DS_Store MacOS files and also r…
moveit/moveit2 pull request #2705
Opened 2024-02-23 13:51 UTC by utkarshanand140

Fixes a part of #871 
Replaced unnecessary strings with characters to make compilation faster. 
Also modified the .gitignore file to avoid tracking .DS_Store files which are often generated when working on MacOS systems.

2024-03-04 19:51 UTC, sjahr reviewed
Thanks for these changes. Can you try to fix it everywhere rather than partially? There was an abandoned PR that attempted the same you could pick up and bring over the finish line

2024-03-05 06:43 UTC, utkarshanand140 commented
> Thanks for these changes. Can you try to fix it everywhere rather than partially? There was an abandoned PR that attempted the same you could pick up and bring over the finish line

Yes sure, I'll be happy to complete it.

2024-05-01 15:44 UTC, EzraBrooks requested changes
Please break these changes out into two PRs - I'd be happy to approve and merge the `.gitignore` change separately from the code changes.

2024-12-02 12:53 UTC, closed without merging

2024-12-02 12:53 UTC, EzraBrooks commented
The bots are now conversing with each other..

I'm closing this PR since it seems unlikely at this point that the feedback will be addressed.